// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngsornqieucsjtbhnubu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nc29ybnFpZXVjc2p0YmhudWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjI0OTUsImV4cCI6MjA2NDYzODQ5NX0.f-MzECaHArb52S1EO3oSA9IbqhnPlf3iMSbaFymuUCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);